version: '2'
services:
  nginx:
    image: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    restart: always
    volumes:
      - $PWD/nginx/conf.d:/etc/nginx/conf.d:ro
    links:
      - app
  app:
    depends_on:
      - db
    build:
      context: ./go
    image: golang:myapp
    volumes:
      - $PWD/go/src/app:/go/src/app
    command: godo server --watch
    restart: always
    links:
      - db
  db:
    build:
      context: ./mysql
    image: mysql/custom:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    volumes:
      # 初回時のみ実行するsqlファイルを格納するディレクトリ
      - $PWD/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    volumes_from:
      - busybox_db
  busybox_db:
    image: busybox
    volumes:
      - /var/lib/mysql
