version: '2'
services:
  nginx:
    image: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    restart: always
    volumes:
      - $PWD/nginx/conf.d:/etc/nginx/conf.d:ro
    links:
      - app
  app:
    build:
      context: ./go
    image: golang:myapp
    depends_on:
      - db
    volumes:
      - $PWD/go/src/app:/go/src/app
    command: godo server --watch
    restart: always
    links:
      - db
  db:
    build:
      context: ./mysql
    image: mysql/custom:5.7
    environment:
      # please change root password
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    volumes:
      # initial execute sql directory
      - $PWD/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # share for host. (please change volume(comment out under) if product host)
      - $PWD/mysql/data:/var/lib/mysql
#    volumes_from:
#      - busybox_db
#  busybox_db:
#    image: busybox
#    volumes:
#      - /var/lib/mysql
